name: Deploy backend to Yandex Serverless Containers

on:
  push:
    branches:
      - master

env:
  CR_REGISTRY: cr.yandex/crp4odt1er9cmqarghdb
  IMAGE_NAME: linni-back

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t $CR_REGISTRY/$IMAGE_NAME:${{ github.sha }} .
          docker tag $CR_REGISTRY/$IMAGE_NAME:${{ github.sha }} $CR_REGISTRY/$IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          docker push $CR_REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push $CR_REGISTRY/$IMAGE_NAME:latest

      - name: Deploy to Yandex Serverless Containers
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: linni-back
          folder-id: b1gslim9pjl5jan2tbod
          revision-image-url: ${{ env.CR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          revision-service-account-id: ajevd85hi4q5rgcernn2
          revision-memory: 512Mb
          revision-core-fraction: 5
          revision-provisioned-instances: 1
          revision-env: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            BOT_NAME=id352826429326_2_bot
            S3_ENDPOINT=https://storage.yandexcloud.net
            S3_ACCESS_KEY=YCAJE39xxesNiBORynLJuwl9V
            S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}
            S3_BUCKET=linni
            DEBUG=true
            MONIUM_API_KEY=${{ secrets.MONIUM_API_KEY }}
            MONIUM_FOLDER_ID=b1gslim9pjl5jan2tbod
